baseURL = "https://www.schmopera.com"
languageCode = "en-us"
title = "Schmopera"
theme = "schmopera"

[taxonomies]
  category = "categories"

[permalinks]
  articles = "/:slug"


[related]
  includeNewer = true

[[related.indices]]
  name = "author"
  toLower = true
  weight = 100.0