---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article
- type: document
  path: content/featured/_index.md
  label: Featured
  templates:
  - featured
- type: directory
  path: content/authors
  label: Authors
  create: documents
  match: "**/*"
  templates:
  - author
- type: directory
  path: content/scene/companies
  label: Companies
  create: documents
  match: "**/*"
  templates:
  - company
- type: directory
  path: content/scene/people
  label: People
  create: documents
  match: "**/*"
  templates:
  - person
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: res/schmopera/image/upload/media
public_path: https://schmopera.imgix.net
front_matter_path: https://schmopera.imgix.net
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
build:
  preview_command: hugo -E -F -D -d public --baseURL="https://u-c18kdygnw7cw.preview.forestry.io"
  publish_command: hugo
  preview_env:
  - HUGO_ENV=Staging
  - HUGO_VERSION=0.52
  publish_env:
  - HUGO_ENV=Production
  - HUGO_VERSION=0.52
  preview_output_directory: public
  output_directory: public
version: '0.52'
